# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebEwelfare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebEwelfare

  target 'WebEwelfareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebEwelfareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'SnapKit'

  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReactorKit'
end
