# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eWelfare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eWelfare
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  
  pod 'SideMenu'
  
  pod 'SDWebImage'
  
  pod 'SwiftGifOrigin', '~> 1.7.0'

end
